// src/lib/components/PrevNextArticle/index.tsx
import styles from "./prev-next-article.module.css";
import { ArrowLeft } from "@/lib/icons/ArrowLeft";
import { ArrowRight } from "@/lib/icons/ArrowRight";
import Link from "next/link";

type PrevNextArticleProps = {
	nextSlug: string | null;
	prevSlug: string | null;
}

export function PrevNextArticle({ prevSlug, nextSlug }: PrevNextArticleProps) {
	return (
		<div className={`${styles["prev-next-article"]} container`}>
			{
				prevSlug
					? <nav>
						<ArrowLeft /> <Link href={`/${prevSlug}`}>Poprzedni artykuł</Link>
					</nav>
					: <div />
			}
			{
				nextSlug && <nav>
					<Link href={`/${nextSlug}`}>Kolejny artykuł</Link>
					<ArrowRight />
				</nav>
			}
		</div>
	);
}

// src/lib/components/PrevNextArticle.svelte
<script lang="ts">
	import ArrowLeft from '$lib/icons/ArrowLeft.svelte';
	import ArrowRight from '$lib/icons/ArrowRight.svelte';

	export let nextSlug: string | null;
	export let prevSlug: string | null;
</script>

<div class="container">
	{#if prevSlug}
		<nav>
			<ArrowLeft /> <a href={`/${prevSlug}`}>Poprzedni artykuł</a>
		</nav>
	{:else}
		<div />
	{/if}

	{#if nextSlug}
		<nav>
			<a href={`/${nextSlug}`}>Kolejny artykuł</a>
			<ArrowRight />
		</nav>
	{/if}
</div>

<style>
	div {
		display: flex;
		justify-content: space-between;
		padding: 1em 0;
	}
</style>
