// src/lib/layout/Navbar/index.tsx
"use client";
import "./style.css";

import { useUiStore } from "@/context/useUiStore";
import { FacebookIcon } from "@/lib/icons/FacebookIcon";
import { LinkedInIcon } from "@/lib/icons/LinkedInIcon";
import { MoonIcon } from "@/lib/icons/MoonIcon";
import { SunIcon } from "@/lib/icons/SunIcon";
import { ThreeDotsHorizontal } from "@/lib/icons/ThreeDotsHorizontal";
import { ThreeDotsVertical } from "@/lib/icons/ThreeDotsVertical";
import Link from "next/link";
import { useEffect, useState } from "react";

type Theme = "light" | "dark";

export function Navbar() {
	const { showOffset, setShowOffset, isIndexPage, isScreenLessThan992 } =
		useUiStore();
	const [theme, setTheme] = useState<Theme>();
	const [isNavbarExpanded, setIsNavbarExpanded] = useState(false);

	function saveTheme(t: Theme) {
		document.documentElement.setAttribute("data-theme", t);
		localStorage.setItem("theme", t);
		setTheme(t);
	}

	function switchMode() {
		if (!theme) return;

		saveTheme(theme === "light" ? "dark" : "light");
	}

	function toggleNavbar() {
		if (!isScreenLessThan992) return;

		setIsNavbarExpanded(!isNavbarExpanded);
	}

	useEffect(() => {
		const themeFromLocalStorage = localStorage.getItem("theme");
		const themeFromHtmlAttribute = document.documentElement.getAttribute(
			"data-theme"
		) as Theme; // THEME IS HARDCODED

		if (theme) return console.log("theme:", theme);

		// if no theme, get theme from local storage
		if (themeFromLocalStorage) return saveTheme(themeFromLocalStorage as Theme);

		// if no theme from local strorage, get theme from html attr
		saveTheme(themeFromHtmlAttribute as Theme);
	}, [theme]);

	return (
		<header id="navbar">
			<div className="container">
				<div className="header-content">
					<div
						className="left-section"
						style={{ display: isIndexPage ? "none" : "inline" }}
					>
						{/* <!-- MENU TOGGLE --> */}
						<span
							onClick={() => setShowOffset(!showOffset)}
							className="icon"
							id="menu-toggle"
						>
							{showOffset ? <ThreeDotsHorizontal /> : <ThreeDotsVertical />}
						</span>
					</div>

					<div className="center-section">
						{/* <!-- NAV BRAND --> */}
						<Link href="/" id="nav-brand" className="nav-link">
							<strong>kodujemywbiurze.pl</strong>
						</Link>
					</div>

					<div className="right-section">
						{!isScreenLessThan992 && (
							<>
								<a href="/kursy/javascript" className="nav-link">
									1️⃣ js
								</a>
								<a href="/kursy/local-storage" className="nav-link">
									2️⃣ storage
								</a>
								<a href="/kursy/html" className="nav-link">
									3️⃣ html
								</a>
								<a href="/kursy/html-javascript-dom" className="nav-link">
									4️⃣ html + js
								</a>
							</>
						)}

						{/* <!-- THEME TOGGLE --> */}
						<span
							onClick={switchMode}
							className="icon nav-link"
							id="theme-toggle"
						>
							{theme === "dark" ? <SunIcon /> : <MoonIcon />}
						</span>

						{!isScreenLessThan992 && (
							<>
								<a
									href="https://www.facebook.com/kodujemywbiurze"
									target="_blank"
									className="nav-link"
								>
									<FacebookIcon />
								</a>
								<a
									href="https://www.linkedin.com/company/kodujemywbiurze"
									target="_blank"
									className="nav-link"
								>
									<LinkedInIcon />
								</a>
							</>
						)}

						{/* <!-- NAVBAR TOGGLE --> */}
						<span
							style={{
								display: !isScreenLessThan992 ? "none" : "inline",
								paddingLeft: isScreenLessThan992 ? "0.5em" : "",
							}}
							onClick={toggleNavbar}
							className="icon"
							id="navbar-toggle"
						>
							{isNavbarExpanded ? (
								<ThreeDotsHorizontal />
							) : (
								<ThreeDotsVertical />
							)}
						</span>
					</div>
				</div>

				{isScreenLessThan992 && isNavbarExpanded && (
					<>
						<hr />
						<div className="expanded-nav-section">
							<a
								href="/kursy/javascript"
								className="nav-link"
								onClick={toggleNavbar}
							>
								1️⃣ javascript
							</a>
							<a
								href="/kursy/local-storage"
								className="nav-link"
								onClick={toggleNavbar}
							>
								2️⃣ local storage
							</a>
							<a href="/kursy/html" className="nav-link" onClick={toggleNavbar}>
								3️⃣ html
							</a>
							<a
								href="/kursy/html-javascript-dom"
								className="nav-link"
								onClick={toggleNavbar}
							>
								4️⃣ html + javascript
							</a>

							<hr />

							<a
								href="https://www.facebook.com/kodujemywbiurze"
								target="_blank"
								className="nav-link"
							>
								<FacebookIcon />
							</a>
							<a
								href="https://www.linkedin.com/company/kodujemywbiurze"
								target="_blank"
								className="nav-link"
							>
								<LinkedInIcon />
							</a>
							<hr style={{ visibility: "hidden" }} />
						</div>
					</>
				)}
			</div>
		</header>
	);
}

// src/lib/components/layout/Navbar.svelte
<script lang="ts">
	import MoonIcon from '$lib/components/icons/MoonIcon.svelte';
	import SunIcon from '$lib/components/icons/SunIcon.svelte';
	import { onMount } from 'svelte';

	let theme: 'light' | 'dark';

	function switchMode() {
		if (theme === 'light') {
			document.documentElement.setAttribute('data-theme', 'dark');
			localStorage.setItem('theme', 'dark');
			theme = 'dark';
		} else {
			document.documentElement.setAttribute('data-theme', 'light');
			localStorage.setItem('theme', 'light');
			theme = 'light';
		}
	}

	onMount(() => {
		theme = document.documentElement.getAttribute('data-theme') as 'light' | 'dark';
	});
</script>

<header class="header-container">
	<div class="header-content">
		<div><a href="/" id="nav-brand"><strong>Kodujemy w biurze</strong></a></div>
		<div>
			<span on:click={switchMode} id="theme-icon">
				{#if theme === 'dark'}
					<SunIcon />
				{:else}
					<MoonIcon />
				{/if}
			</span>
		</div>
	</div>
</header>

<style>
	.header-container {
		position: fixed;
		left: 0;
		right: 0;
		padding: 0 1em;

		width: auto;
		height: 40px;
	}

	.header-content {
		display: flex;
		justify-content: space-between;
		color: white;
	}

	#nav-brand {
		text-decoration: none;
		font-size: large;
	}

	.header-content a,
	#theme-icon {
		color: white;
	}

	.header-content a:hover,
	#theme-icon:hover {
		color: rgba(255, 255, 255, 0.7);
	}

	#theme-icon {
		cursor: pointer;
	}
</style>
